apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terragoat
  annotations:
    github.com/project-slug: ruchabhange/terragoat
spec:
  type: other
  lifecycle: unknown
  owner: guests
